namespace WikidataEditor.Models
{
    public class LanguageCodes
    {
        /// <summary>
        /// Main language codes
        /// </summary>
        public string en { get; set; }
        public string nl { get; set; }
        public string de { get; set; }
        public string fr { get; set; }
        public string es { get; set; }
        public string it { get; set; }

        /// <summary>
        /// Other language codes
        /// </summary>
        public string aa { get; set; }
        public string ab { get; set; }
        public string abe { get; set; }
        public string abq { get; set; }
        public string abs { get; set; }
        public string ace { get; set; }
        public string acm { get; set; }
        public string adx { get; set; }
        public string ady { get; set; }
        public string aeb { get; set; }
        public string af { get; set; }
        public string agq { get; set; }
        public string ajp { get; set; }
        public string ak { get; set; }
        public string akl { get; set; }
        public string akz { get; set; }
        public string aln { get; set; }
        public string als { get; set; }
        public string alt { get; set; }
        public string am { get; set; }
        public string ami { get; set; }
        public string an { get; set; }
        public string ang { get; set; }
        public string anp { get; set; }
        public string aoc { get; set; }
        public string apc { get; set; }
        public string ar { get; set; }
        public string arc { get; set; }
        public string arn { get; set; }
        public string arq { get; set; }
        public string ary { get; set; }
        public string arz { get; set; }
        public string ase { get; set; }
        public string ast { get; set; }
        public string atj { get; set; }
        public string av { get; set; }
        public string avk { get; set; }
        public string awa { get; set; }
        public string ay { get; set; }
        public string az { get; set; }
        public string azb { get; set; }
        public string ba { get; set; }
        public string bal { get; set; }
        public string ban { get; set; }
        public string bar { get; set; }
        public string bbc { get; set; }
        public string bcc { get; set; }
        public string bcl { get; set; }
        public string bdr { get; set; }
        public string be { get; set; }
        public string bej { get; set; }
        public string bfi { get; set; }
        public string bfq { get; set; }
        public string bg { get; set; }
        public string bgn { get; set; }
        public string bh { get; set; }
        public string bho { get; set; }
        public string bi { get; set; }
        public string bjn { get; set; }
        public string bla { get; set; }
        public string bm { get; set; }
        public string bn { get; set; }
        public string bnn { get; set; }
        public string bo { get; set; }
        public string bpy { get; set; }
        public string bqi { get; set; }
        public string br { get; set; }
        public string brh { get; set; }
        public string brx { get; set; }
        public string bs { get; set; }
        public string bsa { get; set; }
        public string bsk { get; set; }
        public string bss { get; set; }
        public string btm { get; set; }
        public string bto { get; set; }
        public string bug { get; set; }
        public string bxr { get; set; }
        public string byq { get; set; }
        public string bzg { get; set; }
        public string bzs { get; set; }
        public string ca { get; set; }
        public string cak { get; set; }
        public string cal { get; set; }
        public string ccp { get; set; }
        public string cdo { get; set; }
        public string ce { get; set; }
        public string ceb { get; set; }
        public string ch { get; set; }
        public string chn { get; set; }
        public string cho { get; set; }
        public string chr { get; set; }
        public string chu { get; set; }
        public string chy { get; set; }
        public string ckb { get; set; }
        public string ckt { get; set; }
        public string ckv { get; set; }
        public string clc { get; set; }
        public string cnh { get; set; }
        public string cnr { get; set; }
        public string co { get; set; }
        public string cop { get; set; }
        public string cps { get; set; }
        public string cpx { get; set; }
        public string cr { get; set; }
        public string crh { get; set; }
        public string crl { get; set; }
        public string crs { get; set; }
        public string cs { get; set; }
        public string csb { get; set; }
        public string ctg { get; set; }
        public string cu { get; set; }
        public string cv { get; set; }
        public string cy { get; set; }
        public string da { get; set; }
        public string dag { get; set; }
        public string dar { get; set; }
        public string din { get; set; }
        public string diq { get; set; }
        public string dlm { get; set; }
        public string dru { get; set; }
        public string dsb { get; set; }
        public string dtp { get; set; }
        public string dty { get; set; }
        public string dua { get; set; }
        public string dv { get; set; }
        public string dz { get; set; }
        public string ee { get; set; }
        public string efi { get; set; }
        public string egl { get; set; }
        public string el { get; set; }
        public string eml { get; set; }
        public string enm { get; set; }
        public string eo { get; set; }
        public string esu { get; set; }
        public string et { get; set; }
        public string ett { get; set; }
        public string eu { get; set; }
        public string ext { get; set; }
        public string eya { get; set; }
        public string fa { get; set; }
        public string ff { get; set; }
        public string fi { get; set; }
        public string fit { get; set; }
        public string fj { get; set; }
        public string fkv { get; set; }
        public string fo { get; set; }
        public string fon { get; set; }
        public string fos { get; set; }
        public string frc { get; set; }
        public string frm { get; set; }
        public string fro { get; set; }
        public string frp { get; set; }
        public string frr { get; set; }
        public string fuf { get; set; }
        public string fur { get; set; }
        public string fy { get; set; }
        public string ga { get; set; }
        public string gaa { get; set; }
        public string gag { get; set; }
        public string gan { get; set; }
        public string gcf { get; set; }
        public string gd { get; set; }
        public string gez { get; set; }
        public string gil { get; set; }
        public string gl { get; set; }
        public string glk { get; set; }
        public string gmh { get; set; }
        public string gml { get; set; }
        public string gn { get; set; }
        public string goh { get; set; }
        public string gom { get; set; }
        public string gor { get; set; }
        public string got { get; set; }
        public string gpe { get; set; }
        public string grc { get; set; }
        public string gsg { get; set; }
        public string gsw { get; set; }
        public string gu { get; set; }
        public string guc { get; set; }
        public string guw { get; set; }
        public string gv { get; set; }
        public string ha { get; set; }
        public string hai { get; set; }
        public string hak { get; set; }
        public string haw { get; set; }
        public string hbo { get; set; }
        public string he { get; set; }
        public string hi { get; set; }
        public string hif { get; set; }
        public string hil { get; set; }
        public string hno { get; set; }
        public string ho { get; set; }
        public string hoc { get; set; }
        public string hr { get; set; }
        public string hrx { get; set; }
        public string hsb { get; set; }
        public string ht { get; set; }
        public string hu { get; set; }
        public string hy { get; set; }
        public string hyw { get; set; }
        public string hz { get; set; }
        public string ia { get; set; }
        public string id { get; set; }
        public string ie { get; set; }
        public string ig { get; set; }
        public string ii { get; set; }
        public string ik { get; set; }
        public string ilo { get; set; }
        public string inh { get; set; }
        public string io { get; set; }
        public string iu { get; set; }
        public string ja { get; set; }
        public string jam { get; set; }
        public string jax { get; set; }
        public string jbo { get; set; }
        public string jut { get; set; }
        public string jv { get; set; }
        public string ka { get; set; }
        public string kaa { get; set; }
        public string kab { get; set; }
        public string kae { get; set; }
        public string kbd { get; set; }
        public string kbg { get; set; }
        public string kbp { get; set; }
        public string kcg { get; set; }
        public string kea { get; set; }
        public string kg { get; set; }
        public string kha { get; set; }
        public string khg { get; set; }
        public string khw { get; set; }
        public string ki { get; set; }
        public string kiu { get; set; }
        public string kj { get; set; }
        public string kjg { get; set; }
        public string kjh { get; set; }
        public string kjp { get; set; }
        public string kk { get; set; }
        public string kl { get; set; }
        public string km { get; set; }
        public string kn { get; set; }
        public string ko { get; set; }
        public string koi { get; set; }
        public string koy { get; set; }
        public string kr { get; set; }
        public string krc { get; set; }
        public string kri { get; set; }
        public string krj { get; set; }
        public string krl { get; set; }
        public string krx { get; set; }
        public string ks { get; set; }
        public string ksh { get; set; }
        public string ksw { get; set; }
        public string ku { get; set; }
        public string kum { get; set; }
        public string kut { get; set; }
        public string kv { get; set; }
        public string kvr { get; set; }
        public string kw { get; set; }
        public string ky { get; set; }
        public string la { get; set; }
        public string lad { get; set; }
        public string lag { get; set; }
        public string lb { get; set; }
        public string lbe { get; set; }
        public string lez { get; set; }
        public string lfn { get; set; }
        public string lg { get; set; }
        public string li { get; set; }
        public string lij { get; set; }
        public string liv { get; set; }
        public string lki { get; set; }
        public string lkt { get; set; }
        public string lld { get; set; }
        public string lmo { get; set; }
        public string ln { get; set; }
        public string lo { get; set; }
        public string loz { get; set; }
        public string lrc { get; set; }
        public string lt { get; set; }
        public string ltg { get; set; }
        public string lus { get; set; }
        public string luz { get; set; }
        public string lv { get; set; }
        public string lvk { get; set; }
        public string lzh { get; set; }
        public string lzz { get; set; }
        public string mad { get; set; }
        public string mai { get; set; }
        public string mdf { get; set; }
        public string mfe { get; set; }
        public string mg { get; set; }
        public string mh { get; set; }
        public string mhr { get; set; }
        public string mi { get; set; }
        public string mic { get; set; }
        public string min { get; set; }
        public string mis { get; set; }
        public string mk { get; set; }
        public string ml { get; set; }
        public string mn { get; set; }
        public string mnc { get; set; }
        public string mni { get; set; }
        public string mnw { get; set; }
        public string mo { get; set; }
        public string moe { get; set; }
        public string mr { get; set; }
        public string mrh { get; set; }
        public string mrj { get; set; }
        public string ms { get; set; }
        public string mt { get; set; }
        public string mui { get; set; }
        public string mul { get; set; }
        public string mus { get; set; }
        public string mwl { get; set; }
        public string mwv { get; set; }
        public string my { get; set; }
        public string myv { get; set; }
        public string mzn { get; set; }
        public string na { get; set; }
        public string nah { get; set; }
        public string nan { get; set; }
        public string nap { get; set; }
        public string nb { get; set; }
        public string nds { get; set; }
        public string ne { get; set; }
        public string ng { get; set; }
        public string nia { get; set; }
        public string niu { get; set; }
        public string nn { get; set; }
        public string no { get; set; }
        public string nod { get; set; }
        public string nog { get; set; }
        public string non { get; set; }
        public string nov { get; set; }
        public string nqo { get; set; }
        public string nr { get; set; }
        public string nrm { get; set; }
        public string nsk { get; set; }
        public string nso { get; set; }
        public string nui { get; set; }
        public string nv { get; set; }
        public string nxm { get; set; }
        public string ny { get; set; }
        public string nys { get; set; }
        public string oc { get; set; }
        public string oj { get; set; }
        public string olo { get; set; }
        public string om { get; set; }
        public string ood { get; set; }
        public string or { get; set; }
        public string os { get; set; }
        public string osa { get; set; }
        public string ota { get; set; }
        public string otk { get; set; }
        public string ovd { get; set; }
        public string pa { get; set; }
        public string pag { get; set; }
        public string pam { get; set; }
        public string pap { get; set; }
        public string pcd { get; set; }
        public string pdc { get; set; }
        public string pdt { get; set; }
        public string peo { get; set; }
        public string pfl { get; set; }
        public string pi { get; set; }
        public string pih { get; set; }
        public string pis { get; set; }
        public string pjt { get; set; }
        public string pko { get; set; }
        public string pl { get; set; }
        public string pms { get; set; }
        public string pmy { get; set; }
        public string pnb { get; set; }
        public string pnt { get; set; }
        public string ppu { get; set; }
        public string prg { get; set; }
        public string ps { get; set; }
        public string pt { get; set; }
        public string pwn { get; set; }
        public string pyu { get; set; }
        public string qu { get; set; }
        public string quc { get; set; }
        public string qug { get; set; }
        public string qya { get; set; }
        public string rar { get; set; }
        public string rcf { get; set; }
        public string rgn { get; set; }
        public string rif { get; set; }
        public string rki { get; set; }
        public string rkt { get; set; }
        public string rm { get; set; }
        public string rmc { get; set; }
        public string rmf { get; set; }
        public string rmy { get; set; }
        public string rn { get; set; }
        public string ro { get; set; }
        public string ru { get; set; }
        public string rue { get; set; }
        public string rup { get; set; }
        public string ruq { get; set; }
        public string rw { get; set; }
        public string rwr { get; set; }
        public string ryu { get; set; }
        public string sa { get; set; }
        public string sah { get; set; }
        public string sat { get; set; }
        public string sc { get; set; }
        public string scn { get; set; }
        public string sco { get; set; }
        public string sd { get; set; }
        public string sdc { get; set; }
        public string sdh { get; set; }
        public string se { get; set; }
        public string sei { get; set; }
        public string ses { get; set; }
        public string sg { get; set; }
        public string sh { get; set; }
        public string shi { get; set; }
        public string shn { get; set; }
        public string shy { get; set; }
        public string si { get; set; }
        public string sid { get; set; }
        public string simple { get; set; }
        public string sjd { get; set; }
        public string sje { get; set; }
        public string sjm { get; set; }
        public string sjn { get; set; }
        public string sjt { get; set; }
        public string sju { get; set; }
        public string sk { get; set; }
        public string skr { get; set; }
        public string sl { get; set; }
        public string sli { get; set; }
        public string sm { get; set; }
        public string sma { get; set; }
        public string smj { get; set; }
        public string smn { get; set; }
        public string sms { get; set; }
        public string sn { get; set; }
        public string so { get; set; }
        public string sou { get; set; }
        public string sq { get; set; }
        public string sr { get; set; }
        public string srn { get; set; }
        public string srq { get; set; }
        public string ss { get; set; }
        public string ssf { get; set; }
        public string st { get; set; }
        public string sth { get; set; }
        public string stq { get; set; }
        public string sty { get; set; }
        public string su { get; set; }
        public string sv { get; set; }
        public string sw { get; set; }
        public string sxr { get; set; }
        public string syc { get; set; }
        public string syl { get; set; }
        public string szl { get; set; }
        public string szy { get; set; }
        public string ta { get; set; }
        public string tay { get; set; }
        public string tce { get; set; }
        public string tcy { get; set; }
        public string te { get; set; }
        public string tet { get; set; }
        public string tg { get; set; }
        public string th { get; set; }
        public string ti { get; set; }
        public string tk { get; set; }
        public string tl { get; set; }
        public string tlh { get; set; }
        public string tli { get; set; }
        public string tly { get; set; }
        public string tn { get; set; }
        public string to { get; set; }
        public string tok { get; set; }
        public string tpi { get; set; }
        public string tr { get; set; }
        public string tru { get; set; }
        public string trv { get; set; }
        public string ts { get; set; }
        public string tsg { get; set; }
        public string tsk { get; set; }
        public string tsu { get; set; }
        public string tt { get; set; }
        public string ttm { get; set; }
        public string tum { get; set; }
        public string tup { get; set; }
        public string tvl { get; set; }
        public string tvn { get; set; }
        public string tvx { get; set; }
        public string tw { get; set; }
        public string ty { get; set; }
        public string tyv { get; set; }
        public string tzl { get; set; }
        public string tzm { get; set; }
        public string udm { get; set; }
        public string ug { get; set; }
        public string uk { get; set; }
        public string umu { get; set; }
        public string und { get; set; }
        public string ur { get; set; }
        public string uun { get; set; }
        public string uz { get; set; }
        public string uzs { get; set; }
        public string ve { get; set; }
        public string vec { get; set; }
        public string vep { get; set; }
        public string vi { get; set; }
        public string vls { get; set; }
        public string vmf { get; set; }
        public string vo { get; set; }
        public string vot { get; set; }
        public string vro { get; set; }
        public string wa { get; set; }
        public string wal { get; set; }
        public string war { get; set; }
        public string wbl { get; set; }
        public string wen { get; set; }
        public string wls { get; set; }
        public string wo { get; set; }
        public string wuu { get; set; }
        public string wya { get; set; }
        public string wym { get; set; }
        public string xal { get; set; }
        public string xh { get; set; }
        public string xmf { get; set; }
        public string xnb { get; set; }
        public string xpu { get; set; }
        public string xsy { get; set; }
        public string yai { get; set; }
        public string yap { get; set; }
        public string yav { get; set; }
        public string ydg { get; set; }
        public string yec { get; set; }
        public string yi { get; set; }
        public string yo { get; set; }
        public string yoi { get; set; }
        public string yrk { get; set; }
        public string yrl { get; set; }
        public string yue { get; set; }
        public string za { get; set; }
        public string zea { get; set; }
        public string zgh { get; set; }
        public string zh { get; set; }
        public string zu { get; set; }
        public string zun { get; set; }
        public string zxx { get; set; }
    }
}
