namespace WikidataEditor.Models
{
    public class Sitelinks
    {
        /// <summary>
        /// Main wikipedia codes
        /// </summary>
        public Sitelink enwiki { get; set; }
        public Sitelink nlwiki { get; set; }
        public Sitelink dewiki { get; set; }
        public Sitelink frwiki { get; set; }
        public Sitelink eswiki { get; set; }
        public Sitelink itwiki { get; set; }

        /// <summary>
        /// Other wikipedia codes
        /// </summary>
        public Sitelink abwiki { get; set; }
        public Sitelink acewiki { get; set; }
        public Sitelink adywiki { get; set; }
        public Sitelink afwiki { get; set; }
        public Sitelink alswiki { get; set; }
        public Sitelink altwiki { get; set; }
        public Sitelink amwiki { get; set; }
        public Sitelink amiwiki { get; set; }
        public Sitelink anwiki { get; set; }
        public Sitelink angwiki { get; set; }
        public Sitelink anpwiki { get; set; }
        public Sitelink arwiki { get; set; }
        public Sitelink arcwiki { get; set; }
        public Sitelink arywiki { get; set; }
        public Sitelink arzwiki { get; set; }
        public Sitelink aswiki { get; set; }
        public Sitelink astwiki { get; set; }
        public Sitelink atjwiki { get; set; }
        public Sitelink avwiki { get; set; }
        public Sitelink avkwiki { get; set; }
        public Sitelink awawiki { get; set; }
        public Sitelink aywiki { get; set; }
        public Sitelink azwiki { get; set; }
        public Sitelink azbwiki { get; set; }
        public Sitelink bawiki { get; set; }
        public Sitelink banwiki { get; set; }
        public Sitelink barwiki { get; set; }
        public Sitelink bclwiki { get; set; }
        public Sitelink bewiki { get; set; }
        public Sitelink bgwiki { get; set; }
        public Sitelink bhwiki { get; set; }
        public Sitelink biwiki { get; set; }
        public Sitelink bjnwiki { get; set; }
        public Sitelink blkwiki { get; set; }
        public Sitelink bmwiki { get; set; }
        public Sitelink bnwiki { get; set; }
        public Sitelink bowiki { get; set; }
        public Sitelink bpywiki { get; set; }
        public Sitelink brwiki { get; set; }
        public Sitelink bswiki { get; set; }
        public Sitelink bugwiki { get; set; }
        public Sitelink bxrwiki { get; set; }
        public Sitelink cawiki { get; set; }
        public Sitelink cdowiki { get; set; }
        public Sitelink cewiki { get; set; }
        public Sitelink cebwiki { get; set; }
        public Sitelink chwiki { get; set; }
        public Sitelink chrwiki { get; set; }
        public Sitelink chywiki { get; set; }
        public Sitelink ckbwiki { get; set; }
        public Sitelink cowiki { get; set; }
        public Sitelink crwiki { get; set; }
        public Sitelink crhwiki { get; set; }
        public Sitelink cswiki { get; set; }
        public Sitelink csbwiki { get; set; }
        public Sitelink cuwiki { get; set; }
        public Sitelink cvwiki { get; set; }
        public Sitelink cywiki { get; set; }
        public Sitelink dawiki { get; set; }
        public Sitelink dagwiki { get; set; }
        public Sitelink dinwiki { get; set; }
        public Sitelink diqwiki { get; set; }
        public Sitelink dsbwiki { get; set; }
        public Sitelink dtywiki { get; set; }
        public Sitelink dvwiki { get; set; }
        public Sitelink dzwiki { get; set; }
        public Sitelink eewiki { get; set; }
        public Sitelink elwiki { get; set; }
        public Sitelink emlwiki { get; set; }
        public Sitelink eowiki { get; set; }
        public Sitelink etwiki { get; set; }
        public Sitelink euwiki { get; set; }
        public Sitelink extwiki { get; set; }
        public Sitelink fawiki { get; set; }
        public Sitelink ffwiki { get; set; }
        public Sitelink fiwiki { get; set; }
        public Sitelink fjwiki { get; set; }
        public Sitelink fowiki { get; set; }
        public Sitelink frpwiki { get; set; }
        public Sitelink frrwiki { get; set; }
        public Sitelink furwiki { get; set; }
        public Sitelink fywiki { get; set; }
        public Sitelink gawiki { get; set; }
        public Sitelink gagwiki { get; set; }
        public Sitelink ganwiki { get; set; }
        public Sitelink gcrwiki { get; set; }
        public Sitelink gdwiki { get; set; }
        public Sitelink glwiki { get; set; }
        public Sitelink glkwiki { get; set; }
        public Sitelink gnwiki { get; set; }
        public Sitelink gomwiki { get; set; }
        public Sitelink gorwiki { get; set; }
        public Sitelink gotwiki { get; set; }
        public Sitelink guwiki { get; set; }
        public Sitelink guwwiki { get; set; }
        public Sitelink gvwiki { get; set; }
        public Sitelink hawiki { get; set; }
        public Sitelink hakwiki { get; set; }
        public Sitelink hawwiki { get; set; }
        public Sitelink hewiki { get; set; }
        public Sitelink hiwiki { get; set; }
        public Sitelink hifwiki { get; set; }
        public Sitelink hrwiki { get; set; }
        public Sitelink hsbwiki { get; set; }
        public Sitelink htwiki { get; set; }
        public Sitelink huwiki { get; set; }
        public Sitelink hywiki { get; set; }
        public Sitelink hywwiki { get; set; }
        public Sitelink iawiki { get; set; }
        public Sitelink idwiki { get; set; }
        public Sitelink iewiki { get; set; }
        public Sitelink igwiki { get; set; }
        public Sitelink ikwiki { get; set; }
        public Sitelink ilowiki { get; set; }
        public Sitelink inhwiki { get; set; }
        public Sitelink iowiki { get; set; }
        public Sitelink iswiki { get; set; }
        public Sitelink iuwiki { get; set; }
        public Sitelink jawiki { get; set; }
        public Sitelink jamwiki { get; set; }
        public Sitelink jbowiki { get; set; }
        public Sitelink jvwiki { get; set; }
        public Sitelink kawiki { get; set; }
        public Sitelink kaawiki { get; set; }
        public Sitelink kabwiki { get; set; }
        public Sitelink kbdwiki { get; set; }
        public Sitelink kbpwiki { get; set; }
        public Sitelink kcgwiki { get; set; }
        public Sitelink kgwiki { get; set; }
        public Sitelink kiwiki { get; set; }
        public Sitelink kkwiki { get; set; }
        public Sitelink kmwiki { get; set; }
        public Sitelink knwiki { get; set; }
        public Sitelink kowiki { get; set; }
        public Sitelink koiwiki { get; set; }
        public Sitelink krcwiki { get; set; }
        public Sitelink kswiki { get; set; }
        public Sitelink kshwiki { get; set; }
        public Sitelink kuwiki { get; set; }
        public Sitelink kvwiki { get; set; }
        public Sitelink kwwiki { get; set; }
        public Sitelink kywiki { get; set; }
        public Sitelink lawiki { get; set; }
        public Sitelink ladwiki { get; set; }
        public Sitelink lbwiki { get; set; }
        public Sitelink lbewiki { get; set; }
        public Sitelink lezwiki { get; set; }
        public Sitelink lfnwiki { get; set; }
        public Sitelink lgwiki { get; set; }
        public Sitelink liwiki { get; set; }
        public Sitelink lijwiki { get; set; }
        public Sitelink lldwiki { get; set; }
        public Sitelink lmowiki { get; set; }
        public Sitelink lnwiki { get; set; }
        public Sitelink lowiki { get; set; }
        public Sitelink ltwiki { get; set; }
        public Sitelink ltgwiki { get; set; }
        public Sitelink lvwiki { get; set; }
        public Sitelink madwiki { get; set; }
        public Sitelink maiwiki { get; set; }
        public Sitelink mdfwiki { get; set; }
        public Sitelink mgwiki { get; set; }
        public Sitelink mhrwiki { get; set; }
        public Sitelink miwiki { get; set; }
        public Sitelink minwiki { get; set; }
        public Sitelink mkwiki { get; set; }
        public Sitelink mlwiki { get; set; }
        public Sitelink mnwiki { get; set; }
        public Sitelink mniwiki { get; set; }
        public Sitelink mnwwiki { get; set; }
        public Sitelink mrwiki { get; set; }
        public Sitelink mrjwiki { get; set; }
        public Sitelink mswiki { get; set; }
        public Sitelink mtwiki { get; set; }
        public Sitelink mwlwiki { get; set; }
        public Sitelink mywiki { get; set; }
        public Sitelink myvwiki { get; set; }
        public Sitelink mznwiki { get; set; }
        public Sitelink napwiki { get; set; }
        public Sitelink ndswiki { get; set; }
        public Sitelink newiki { get; set; }
        public Sitelink newwiki { get; set; }
        public Sitelink Ngawiki { get; set; }
        public Sitelink niawiki { get; set; }
        public Sitelink nnwiki { get; set; }
        public Sitelink nowiki { get; set; }
        public Sitelink novwiki { get; set; }
        public Sitelink nqowiki { get; set; }
        public Sitelink nrmwiki { get; set; }
        public Sitelink nsowiki { get; set; }
        public Sitelink nvwiki { get; set; }
        public Sitelink nywiki { get; set; }
        public Sitelink ocwiki { get; set; }
        public Sitelink olowiki { get; set; }
        public Sitelink omwiki { get; set; }
        public Sitelink orwiki { get; set; }
        public Sitelink oswiki { get; set; }
        public Sitelink pawiki { get; set; }
        public Sitelink pagwiki { get; set; }
        public Sitelink pamwiki { get; set; }
        public Sitelink papwiki { get; set; }
        public Sitelink pcdwiki { get; set; }
        public Sitelink pdcwiki { get; set; }
        public Sitelink pflwiki { get; set; }
        public Sitelink piwiki { get; set; }
        public Sitelink pihwiki { get; set; }
        public Sitelink plwiki { get; set; }
        public Sitelink pmswiki { get; set; }
        public Sitelink pnbwiki { get; set; }
        public Sitelink pntwiki { get; set; }
        public Sitelink pswiki { get; set; }
        public Sitelink ptwiki { get; set; }
        public Sitelink quwiki { get; set; }
        public Sitelink rmwiki { get; set; }
        public Sitelink rmywiki { get; set; }
        public Sitelink rnwiki { get; set; }
        public Sitelink rowiki { get; set; }
        public Sitelink ruwiki { get; set; }
        public Sitelink ruewiki { get; set; }
        public Sitelink rwwiki { get; set; }
        public Sitelink sawiki { get; set; }
        public Sitelink sahwiki { get; set; }
        public Sitelink satwiki { get; set; }
        public Sitelink scwiki { get; set; }
        public Sitelink scnwiki { get; set; }
        public Sitelink scowiki { get; set; }
        public Sitelink sdwiki { get; set; }
        public Sitelink sewiki { get; set; }
        public Sitelink sgwiki { get; set; }
        public Sitelink shwiki { get; set; }
        public Sitelink shiwiki { get; set; }
        public Sitelink shnwiki { get; set; }
        public Sitelink siwiki { get; set; }
        public Sitelink skwiki { get; set; }
        public Sitelink skrwiki { get; set; }
        public Sitelink slwiki { get; set; }
        public Sitelink smwiki { get; set; }
        public Sitelink smnwiki { get; set; }
        public Sitelink snwiki { get; set; }
        public Sitelink sowiki { get; set; }
        public Sitelink sqwiki { get; set; }
        public Sitelink srwiki { get; set; }
        public Sitelink srnwiki { get; set; }
        public Sitelink sswiki { get; set; }
        public Sitelink stwiki { get; set; }
        public Sitelink stqwiki { get; set; }
        public Sitelink suwiki { get; set; }
        public Sitelink svwiki { get; set; }
        public Sitelink swwiki { get; set; }
        public Sitelink szlwiki { get; set; }
        public Sitelink szywiki { get; set; }
        public Sitelink tawiki { get; set; }
        public Sitelink taywiki { get; set; }
        public Sitelink tcywiki { get; set; }
        public Sitelink tewiki { get; set; }
        public Sitelink tetwiki { get; set; }
        public Sitelink tgwiki { get; set; }
        public Sitelink thwiki { get; set; }
        public Sitelink tiwiki { get; set; }
        public Sitelink tkwiki { get; set; }
        public Sitelink tlwiki { get; set; }
        public Sitelink tnwiki { get; set; }
        public Sitelink towiki { get; set; }
        public Sitelink tpiwiki { get; set; }
        public Sitelink trwiki { get; set; }
        public Sitelink trvwiki { get; set; }
        public Sitelink tswiki { get; set; }
        public Sitelink ttwiki { get; set; }
        public Sitelink tumwiki { get; set; }
        public Sitelink twwiki { get; set; }
        public Sitelink tywiki { get; set; }
        public Sitelink tyvwiki { get; set; }
        public Sitelink udmwiki { get; set; }
        public Sitelink ugwiki { get; set; }
        public Sitelink ukwiki { get; set; }
        public Sitelink urwiki { get; set; }
        public Sitelink uzwiki { get; set; }
        public Sitelink vewiki { get; set; }
        public Sitelink vecwiki { get; set; }
        public Sitelink vepwiki { get; set; }
        public Sitelink viwiki { get; set; }
        public Sitelink vlswiki { get; set; }
        public Sitelink vowiki { get; set; }
        public Sitelink wawiki { get; set; }
        public Sitelink warwiki { get; set; }
        public Sitelink wowiki { get; set; }
        public Sitelink wuuwiki { get; set; }
        public Sitelink xalwiki { get; set; }
        public Sitelink xhwiki { get; set; }
        public Sitelink xmfwiki { get; set; }
        public Sitelink yiwiki { get; set; }
        public Sitelink yowiki { get; set; }
        public Sitelink zawiki { get; set; }
        public Sitelink zeawiki { get; set; }
        public Sitelink zhwiki { get; set; }
        public Sitelink zuwiki { get; set; }

    }
}
