namespace WikidataEditor.Models
{
    public class P10018 : Statement { }
    public class P1003 : Statement { }
    public class P1005 : Statement { }
    public class P1006 : Statement { }
    public class P10141 : Statement { }
    public class P1015 : Statement { }
    public class P1017 : Statement { }
    public class P102 : Statement { }
    public class P10227 : Statement { }
    public class P10234 : Statement { }
    public class P10242 : Statement { }
    public class P10297 : Statement { }
    public class P103 : Statement { }
    public class P10302 : Statement { }
    public class P10307 : Statement { }
    public class P1048 : Statement { }
    public class P10553 : Statement { }
    public class P10565 : Statement { }
    public class P106 : Statement { }
    public class P10757 : Statement { }
    public class P10789 : Statement { }
    public class P108 : Statement { }
    public class P10832 : Statement { }
    public class P10874 : Statement { }
    public class P10882 : Statement { }
    public class P11155 : Statement { }
    public class P11156 : Statement { }
    public class P11194 : Statement { }
    public class P11239 : Statement { }
    public class P11249 : Statement { }
    public class P11496 : Statement { }
    public class P11514 : Statement { }
    public class P11686 : Statement { }
    public class P1185 : Statement { }
    public class P119 : Statement { }
    public class P1196 : Statement { }
    public class P1207 : Statement { }
    public class P1213 : Statement { }
    public class P1225 : Statement { }
    public class P1233 : Statement { }
    public class P1248 : Statement { }
    public class P1263 : Statement { }
    public class P1273 : Statement { }
    public class P1280 : Statement { }
    public class P1284 : Statement { }
    public class P1296 : Statement { }
    public class P1299 : Statement { }
    public class P1309 : Statement { }
    public class P1315 : Statement { }
    public class P1331 : Statement { }
    public class P1343 : Statement { }
    public class P1367 : Statement { }
    public class P1368 : Statement { }
    public class P1375 : Statement { }
    public class P140 : Statement { }
    public class P1411 : Statement { }
    public class P1412 : Statement { }
    public class P1415 : Statement { }
    public class P1417 : Statement { }
    public class P1430 : Statement { }
    public class P1438 : Statement { }
    public class P1442 : Statement { }
    public class P1449 : Statement { }
    public class P1477 : Statement { }
    public class P1559 : Statement { }
    public class P1564 : Statement { }
    public class P1580 : Statement { }
    public class P1617 : Statement { }
    public class P166 : Statement { }
    public class P1695 : Statement { }
    public class P1711 : Statement { }
    public class P1728 : Statement { }
    public class P1741 : Statement { }
    public class P18 : Statement { }
    public class P1816 : Statement { }
    public class P1819 : Statement { }
    public class P1889 : Statement { }
    public class P1890 : Statement { }
    public class P1899 : Statement { }
    public class P19 : Statement { }
    public class P1938 : Statement { }
    public class P1953 : Statement { }
    public class P1988 : Statement { }
    public class P20 : Statement { }
    public class P2015 : Statement { }
    public class P2042 : Statement { }
    public class P21 : Statement { }
    public class P213 : Statement { }
    public class P214 : Statement { }
    public class P2163 : Statement { }
    public class P2188 : Statement { }
    public class P2191 : Statement { }
    public class P22 : Statement { }
    public class P2268 : Statement { }
    public class P227 : Statement { }
    public class P2354 : Statement { }
    public class P2383 : Statement { }
    public class P241 : Statement { }
    public class P244 : Statement { }
    public class P245 : Statement { }
    public class P25 : Statement { }
    public class P26 : Statement { }
    public class P2600 : Statement { }
    public class P2605 : Statement { }
    public class P2607 : Statement { }
    public class P2639 : Statement { }
    public class P2671 : Statement { }
    public class P268 : Statement { }
    public class P269 : Statement { }
    public class P27 : Statement { }
    public class P270 : Statement { }
    public class P271 : Statement { }
    public class P2741 : Statement { }
    public class P2843 : Statement { }
    public class P2850 : Statement { }
    public class P2888 : Statement { }
    public class P2889 : Statement { }
    public class P2924 : Statement { }
    public class P2941 : Statement { }
    public class P2944 : Statement { }
    public class P2949 : Statement { }
    public class P2963 : Statement { }
    public class P2966 : Statement { }
    public class P3029 : Statement { }
    public class P3051 : Statement { }
    public class P3065 : Statement { }
    public class P31 : Statement { }
    public class P3106 : Statement { }
    public class P3154 : Statement { }
    public class P3192 : Statement { }
    public class P3219 : Statement { }
    public class P3221 : Statement { }
    public class P3222 : Statement { }
    public class P3232 : Statement { }
    public class P3280 : Statement { }
    public class P3348 : Statement { }
    public class P3360 : Statement { }
    public class P3365 : Statement { }
    public class P3368 : Statement { }
    public class P3373 : Statement { }
    public class P3417 : Statement { }
    public class P3430 : Statement { }
    public class P345 : Statement { }
    public class P3478 : Statement { }
    public class P349 : Statement { }
    public class P3544 : Statement { }
    public class P3602 : Statement { }
    public class P3630 : Statement { }
    public class P373 : Statement { }
    public class P3762 : Statement { }
    public class P3782 : Statement { }
    public class P3788 : Statement { }
    public class P3846 : Statement { }
    public class P3847 : Statement { }
    public class P39 : Statement { }
    public class P396 : Statement { }
    public class P3965 : Statement { }
    public class P3987 : Statement { }
    public class P3988 : Statement { }
    public class P40 : Statement { }
    public class P4004 : Statement { }
    public class P409 : Statement { }
    public class P410 : Statement { }
    public class P4104 : Statement { }
    public class P4145 : Statement { }
    public class P4159 : Statement { }
    public class P4200 : Statement { }
    public class P4223 : Statement { }
    public class P4248 : Statement { }
    public class P4293 : Statement { }
    public class P434 : Statement { }
    public class P4342 : Statement { }
    public class P4359 : Statement { }
    public class P4457 : Statement { }
    public class P4471 : Statement { }
    public class P4527 : Statement { }
    public class P4553 : Statement { }
    public class P4589 : Statement { }
    public class P4601 : Statement { }
    public class P4619 : Statement { }
    public class P4629 : Statement { }
    public class P463 : Statement { }
    public class P4638 : Statement { }
    public class P4663 : Statement { }
    public class P4789 : Statement { }
    public class P4804 : Statement { }
    public class P4808 : Statement { }
    public class P4839 : Statement { }
    public class P485 : Statement { }
    public class P4862 : Statement { }
    public class P4927 : Statement { }
    public class P4985 : Statement { }
    public class P5008 : Statement { }
    public class P5019 : Statement { }
    public class P5034 : Statement { }
    public class P5063 : Statement { }
    public class P509 : Statement { }
    public class P511 : Statement { }
    public class P5298 : Statement { }
    public class P535 : Statement { }
    public class P5357 : Statement { }
    public class P5375 : Statement { }
    public class P5421 : Statement { }
    public class P551 : Statement { }
    public class P552 : Statement { }
    public class P5587 : Statement { }
    public class P5597 : Statement { }
    public class P569 : Statement { }
    public class P570 : Statement { } 
    public class P5731 : Statement { }
    public class P5739 : Statement { }
    public class P5821 : Statement { }
    public class P5882 : Statement { }
    public class P5905 : Statement { }
    public class P5909 : Statement { }
    public class P6002 : Statement { }
    public class P6058 : Statement { }
    public class P607 : Statement { }
    public class P6200 : Statement { }
    public class P6255 : Statement { }
    public class P6262 : Statement { }
    public class P6275 : Statement { }
    public class P6379 : Statement { }
    public class P6385 : Statement { }
    public class P6394 : Statement { }
    public class P6404 : Statement { }
    public class P6414 : Statement { }
    public class P646 : Statement { }
    public class P648 : Statement { }
    public class P650 : Statement { }
    public class P651 : Statement { }
    public class P6517 : Statement { }
    public class P6573 : Statement { }
    public class P6621 : Statement { }
    public class P6683 : Statement { }
    public class P6844 : Statement { }
    public class P6886 : Statement { }
    public class P69 : Statement { }
    public class P691 : Statement { }
    public class P701 : Statement { }
    public class P7026 : Statement { }
    public class P7029 : Statement { }
    public class P7039 : Statement { }
    public class P7052 : Statement { }
    public class P7157 : Statement { }
    public class P723 : Statement { }
    public class P7293 : Statement { }
    public class P7305 : Statement { }
    public class P734 : Statement { }
    public class P7349 : Statement { }
    public class P735 : Statement { }
    public class P7369 : Statement { }
    public class P7400 : Statement { }
    public class P7553 : Statement { }
    public class P7699 : Statement { }
    public class P7763 : Statement { }
    public class P7775 : Statement { }
    public class P7779 : Statement { }
    public class P7796 : Statement { }
    public class P7818 : Statement { }
    public class P7827 : Statement { }
    public class P7848 : Statement { }
    public class P7859 : Statement { }
    public class P7865 : Statement { }
    public class P7902 : Statement { }
    public class P7928 : Statement { }
    public class P7929 : Statement { }
    public class P793 : Statement { }
    public class P7982 : Statement { }
    public class P800 : Statement { }
    public class P8024 : Statement { }
    public class P8034 : Statement { }
    public class P8081 : Statement { }
    public class P8094 : Statement { }
    public class P8116 : Statement { }
    public class P8172 : Statement { }
    public class P8179 : Statement { }
    public class P8189 : Statement { }
    public class P8223 : Statement { }
    public class P8234 : Statement { }
    public class P8238 : Statement { }
    public class P8309 : Statement { }
    public class P8313 : Statement { }
    public class P8317 : Statement { }
    public class P8349 : Statement { }
    public class P8408 : Statement { }
    public class P8496 : Statement { }
    public class P8547 : Statement { }
    public class P8568 : Statement { }
    public class P866 : Statement { }
    public class P8750 : Statement { }
    public class P8795 : Statement { }
    public class P8805 : Statement { }
    public class P8814 : Statement { }
    public class P8833 : Statement { }
    public class P8848 : Statement { }
    public class P8849 : Statement { }
    public class P8850 : Statement { }
    public class P8851 : Statement { }
    public class P8885 : Statement { }
    public class P8899 : Statement { }
    public class P8902 : Statement { }
    public class P8980 : Statement { }
    public class P8992 : Statement { }
    public class P902 : Statement { }
    public class P9037 : Statement { }
    public class P906 : Statement { }
    public class P9081 : Statement { }
    public class P910 : Statement { }
    public class P9141 : Statement { }
    public class P9152 : Statement { }
    public class P9164 : Statement { }
    public class P9179 : Statement { }
    public class P9247 : Statement { }
    public class P9251 : Statement { }
    public class P935 : Statement { }
    public class P937 : Statement { }
    public class P9371 : Statement { }
    public class P94 : Statement { }
    public class P9438 : Statement { }
    public class P945 : Statement { }
    public class P947 : Statement { }
    public class P9493 : Statement { }
    public class P9495 : Statement { }
    public class P950 : Statement { }
    public class P9594 : Statement { }
    public class P9629 : Statement { }
    public class P9661 : Statement { }
    public class P9791 : Statement { }
    public class P990 : Statement { }
    public class P9918 : Statement { }
    public class P9965 : Statement { }
    public class P9984 : Statement { }
}